### ISSUE TITLE
script fails with below error.

### ISSUE THREAD

**Issue by protoss1232001** [jbrt/svc2influxdb#3]
See below. Am I missing any modules for this?

./svc2influxdb.py svc2influxdb.conf

Traceback (most recent call last):
  File "./svc2influxdb.py", line 242, in <module>
    series += svc_volume.collect()
  File "./svc2influxdb.py", line 210, in collect
    return [self._builder.parse(line, 'volume') for line in volume_details]
  File "./svc2influxdb.py", line 210, in <listcomp>
    return [self._builder.parse(line, 'volume') for line in volume_details]
  File "./svc2influxdb.py", line 105, in parse
    prefix=prefix))
  File "./svc2influxdb.py", line 82, in _build_series
    'fields': {'value': int(value)}}
ValueError: invalid literal for int() with base 10: ''

**Comment by jbrt** [comment]
Hi @protoss1232001 

It seems not. Are you sure that your are using the right version of Python (3.x)?
You should put a break point between lines 101 and 102 and try to understand why the value of measurement seems to be not good.

I don't work anymore with SVC products and, of course, the software has evolved. Maybe the newer versions are incomptible with that code.

Regards
